### ISSUE TITLE
Allow gamepads to traverse menus

### ISSUE THREAD

**Issue by ReynoldsCahoon** [jake-pauls/Hamstars#59]
Allow the game menus to be navigated with gamepads.

**Comment by jake-pauls** [comment]
This can be implemented in a rudimentary way via script (and was for the jam, not sure why it didn't work):

```
uiButton.Select()
```

If @Kabug is implementing rewired, there won't be much of a point in making a set of UI InputActions with the new input system.

Another way this can work (since we don't have many individual menus) is just by making the Start button the `First Selected` in the Main scene.

![image](https://user-images.githubusercontent.com/48817786/166625971-46fec07a-3fb7-4a5a-ac84-fe47e2dbf1f3.png)
